name: Deploy to EC2

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: loi_test
          SOURCE: .
      with:
        SCRIPT_BEFORE: |
            whoami
            ls -al
            mkdir -p loi_test
        SCRIPT_AFTER: |
          cd loi_test
          ls -al

          echo "Installing PM2..."
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          npm install

          echo "Starting/restarting application..."
          pm2 restart server.js || pm2 start server.js
