name: Deploy to EC2

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  build:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: loi_test
          SOURCE: .
      - name: go to loi_test directory
        run: cd ~/loi_test
      - name: Install dependencies
        run: npm install
      - name: pm2 restart
        run: pm2 restart server || pm2 start server.js --name server
